import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Pontes do Bem</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>

      <main className={styles.main}>
        <p className={styles.subtitle}>
          Bem vindo ao projeto social
        </p>
        <h1 className={styles.title}>
         Pontes do Bem
        </h1>
        <p className={styles.description}>
          Estamos preparando este site para você!
        </p>
      </main>

      <footer className={styles.footer}>
          <span className={styles.footerText}>
           Em desenvolvimento por
          </span>
          
          <a
          href="https://github.com/davivcarvalho"
          target="_blank"
          rel="noopener noreferrer"
        >
          <span className={styles.logo}>
            Davi Carvalho
            <Image src="/github.svg" alt="Vercel Logo" width={30} height={30} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
